### ISSUE TITLE
OpenStreetMap import will break if links aren't updated before May 7

### ISSUE THREAD

**Issue by grischard** [wosch/bbbike-world#2]
http://planet.openstreetmap.org is available over https, and will [start redirecting to https on 2018-05-07](https://github.com/openstreetmap/operations/issues/200).

Your project uses curl, which [will not follow redirects by default](https://davidwalsh.name/curl-follow-redirects).

Would it please be possible to update all files from http://planet.openstreetmap.org to  http**s**://planet.openstreetmap.org before then?

Ideally, would it be possible to make all requests to openstreetmap.org over https?

**Comment by wosch** [comment]
We are using the HTTPS protocol for downloading files from planet.openstreetmap.org for at least 18 month without a problem. 

I will close the issue. Fell free to contact us again if you still see requests to HTTP in your logfiles.

**Comment by grischard** [comment]
Thanks! I do see http:// in bin/planet-download-xml. The `curl` calls in there seem to all use -L, so you should follow the redirects and be fine.
